/**
 * @distilled.cloud/digitalocean — DigitalOcean SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy model
 * in `.generated-specs` (written by `scripts/convert.ts` from the OpenAPI
 * spec). Everything else in this folder is hand-written.
 *
 * @example
 * ```ts
 * import * as DigitalOcean from "@distilled.cloud/digitalocean";
 *
 * const account = yield* DigitalOcean.Services.digitalocean.accountGet({});
 * ```
 */
export * from "./credentials.ts";
export * from "./errors.ts";
export * as T from "./traits.ts";
export {
  DigitalOceanProtocol,
  type DigitalOceanOpError,
  type DigitalOceanOpContext,
} from "./protocol.ts";
export { paginateCursor, paginatePageNumber } from "./pagination.ts";
export * as Retry from "./retry.ts";
export * as Services from "./services/index.ts";
// Operations (and their request/response types) are importable off the package
// root. The service-local typed error classes shadow the same-named shared
// ones from ./errors.ts — the ops actually raise the service-local classes.
//
// The API also models a `Credentials` schema (a database connection's
// user/password), which would collide with the `Credentials` service from
// ./credentials.ts. That one stays at the root; the schema is reachable as
// `Services.digitalocean.Credentials`.
export * from "./services/digitalocean.ts";
export { Credentials } from "./credentials.ts";
export {
  BadRequest,
  Conflict,
  Forbidden,
  NotFound,
  UnprocessableEntity,
} from "./services/digitalocean.ts";
